AAC-0015-web-AllTabs-Styles
raquevedo/AppArCar pull request #121
Opened 2022-10-26 22:51 UTC by JJPasso

Buenas a continuación voy a describir el alcance de este PR:

- Estilizar Tabs Head
- Estilizar Tab Reservation
- Estilizar Tab Status
- Estilizar Tab Hours
- Estilizar Tab Settings
- Correcciones UI de Ustedes 👍

2022-10-28 11:59 UTC, raquevedo commented
Esta muy bueno te agrego un par de comentarios:

- Tenias un conflicto con master, te lo resolvi para poder dejarte el review y que no se pierda pero revisa porfa que no se haya roto nada
- El tab que  esta como active queda en blanco, habria que dejarlo en un color parecido al original pero mas claro
- Adentro del tab de reservations no veo nada de estilo, esta el body entero con html basico

2022-10-28 21:00 UTC, faballay commented
@JJPasso 
FE Web- En home --> Register --> falta el diseño en alerts: succes y error

2022-10-29 15:15 UTC, raquevedo commented
Tenes un flor de conflicto, si necesitas ayuda avisame.

2022-11-01 21:26 UTC, JJPasso commented on frontend_web_service/frontend/src/components/Dashboard/ParkingAccordionContent.js
>            <h3>Manage</h3>
son subclases, asi funciona la logica

2022-11-01 23:24 UTC, billgiberti commented
Observo el siguiente problema.

![imagen](https://user-images.githubusercontent.com/103656600/199360461-7a02345f-70fd-498e-902f-88b879a122c1.png)

Por otro lado los clicks en el el nab responden solo al hacerlos sobre el centro de la solapa pero bueno esto es menor.

2022-11-02 13:45 UTC, raquevedo requested changes

2022-11-02 13:45 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Dashboard/AddParkingModal.js
> +
Saca este espacio

2022-11-02 13:45 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Dashboard/AddParkingModal.js
> +
Aca tambien

2022-11-02 13:45 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Dashboard/ParkingAccordionContent.js
>            <h3>Manage</h3>
No, h3 esta adentro de Link, tiene que ir indentado

2022-11-02 13:45 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/Hours/HoursTab.js
> +        setFromMonday(
Por que cambiaste todo esto?

2022-11-02 13:45 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/Hours/HoursTab.js
> +      <div>
Este div no esta de mas?

2022-11-02 13:45 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/ManagementBoard.js
> +import React, { useEffect } from "react";
Para que cambiaste las comillas del codigo? Trata de mantenerte dentro de lo que es la tarea del branch, esto no hace falta.

2022-11-02 13:45 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/ManagementBoard.js
> +      case "reservations":
Idem, estaba bien antes

2022-11-02 13:45 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/Reservations/PendingReservations.js
> +      <h2 className='text-reservations'>Pending Reservations</h2>
Indentacion

2022-11-02 13:45 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/Settings/SettingsTab.js
>        <ParkingForm
Indentacion

2022-11-02 15:11 UTC, JJPasso commented on frontend_web_service/frontend/src/components/Management/Hours/HoursTab.js
> +        setFromMonday(
what, seguramente lo borre sin querer

2022-11-02 20:00 UTC, raquevedo approved these changes
Creo que estamos para el release pero los botones en los tabs solo se pueden clickear si apretas directo en el texto.

2022-11-02 20:30 UTC, JJPasso commented
listo

2022-11-02 20:34 UTC, raquevedo approved these changes

2022-11-02 22:10 UTC, ManuelArzuaga approved these changes

2022-11-02 22:10 UTC, merged