Aac web profile update
raquevedo/AppArCar pull request #126
Opened 2022-10-28 23:32 UTC by ManuelArzuaga

-cambio de form para cumplir con el endpoint
-validacion al ingresar los datos al hacer click el input
-form tell about you aparece solo la primera vez que se inicia sesion
-en perfil se traen los datos del backend, se pueden modificar los datos
-se validan los datos al ser modificados (bug al hacer click en update sin cambiar ningun dato traido del backend)

2022-10-29 14:13 UTC, faballay requested changes
@ManuelArzuaga 
Un detalle importante: 
Estas trabajando a nivel **usuario** que maneja un parking, no a nivel parking. Creo que los endpoints te deberian haber ayudado a crear nombres significativos. 

Entonces, no estas obteniendo datos de un Parking, sino de un **User**. (Por eso usas el ms de users) 
Corregi la capa semantica de tu codigo.

**Ademas: aprovecha para corregir los nombres de partners tmb** 
Te deberia quedar algo asi al final 
registerUser --> registerPartnerUser  , registerParkingUser
updateUser --> updatePartnerUser , updateParkingUser


Con respecto al **BUG** , es como si no estuvieras asignando nada y enviando los campos vacios. Es un bug del lado del front.

2022-10-29 14:13 UTC, faballay commented on frontend_web_service/frontend/src/controllers/usersController.js
> +  myHeaders.append('Authorization', 'Bearer ' + fetchToken());
Usemos el principio DRY
Fijate como resuelve los headers aca y luego invoca a la funcion

https://github.com/raquevedo/AppArCar/blob/83a7925d4e06bb3b5666d6490b4068d2e2687ca2/frontend_web_service/frontend/src/controllers/parkingController.js#L3

Ahorramos muchas lineas de codigo

2022-10-29 14:13 UTC, faballay commented on frontend_web_service/frontend/src/controllers/usersController.js
> +  let myHeaders = new Headers();
Te lo pongo una vez mas, pero aplicalo a todo el archivo

2022-10-29 14:13 UTC, faballay commented on frontend_web_service/frontend/src/controllers/usersController.js
> +export async function updateParking(parkingData) {
No confundamos, esto no es "updateParking" es "updateParkingUser" o "updateUserParking" 
Estas trabajando a nivel usuario que maneja un parking, no a nivel parking.

2022-10-29 14:13 UTC, faballay commented on frontend_web_service/frontend/src/components/Forms/UserForm.js
> +    async function assignParkingData() {
Estas trabajando a nivel usuario que maneja un parking, no a nivel parking.

2022-10-29 14:13 UTC, faballay commented on frontend_web_service/frontend/src/components/Dashboard/DashboardWrapper.js
> +import { getParkingData }  from '../../controllers/usersController';
getParkingData es incorrecto, getUserParkingData

2022-10-29 14:13 UTC, faballay commented on frontend_web_service/frontend/src/components/Dashboard/DashboardWrapper.js
> +  const [parkingData, setParkingData] = useState({});
Acá tmb, arreglemos la semantica

2022-10-29 14:13 UTC, faballay commented on frontend_web_service/frontend/src/components/Dashboard/DashboardWrapper.js
> +    assignParkingData();
revisala en todo el file.

2022-10-29 15:04 UTC, raquevedo requested changes
No tengo muchos comentarios, mas que nada lo que dijo Fede.

2022-10-29 15:04 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Forms/UserForm.js
> +
Saca estos espacios despues de declarar funciones, en todos los casos

2022-10-29 15:04 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Forms/UserForm.js
> +      const parking = await getParkingData();
Que pasa aca cuando no existen los datos?

2022-10-30 04:18 UTC, ManuelArzuaga commented
-cambios pedidos
-creacion de funcion para resolver el bug

2022-10-31 16:56 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Dashboard/DashboardWrapper.js
> +  const [parkingData, setParkingData] = useState({});
Sigue estando esto aca

2022-10-31 17:06 UTC, raquevedo submitted a review, later dismissed
Hay bastante quilombo adentro del codigo, porfa mira mi PR del componente de settings y usalo de base para armar esto.

Hay que reducir la cantidad de logica que se maneja adentro del form, esto no es reutilizable sino.

2022-10-31 17:08 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Forms/UserForm.js
> +    document.getElementById("button-update-submit").click()
Estas haciendo el post de los datos 2 veces

2022-10-31 21:45 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Forms/UserForm.js
> +  function Focusinput(){
Me volvi medio loco pero encontre como resolver este problema bien. useForm tiene que recibir los default values al iniciarse.

https://github.com/raquevedo/AppArCar/pull/128

Ojo que si le pasas defaults no validos el submit deja de andar sin mensaje de error.

2022-11-02 05:55 UTC, ManuelArzuaga commented
cambie la validacion de la forma en que esta en settings pero estoy teniendo un problema, me esta asignando los valores como undefined, ademas que los valores del backend los trae varias veces primero como undefined y despues trae los valores,
alguna idea de que puede ser ??

2022-11-02 19:25 UTC, raquevedo commented
Ahi tenes que entender bien como funciona el useEffect.

useEffect se ejecuta por primera vez cuando se termina de renderizar el componente y cada vez que se active un evento que le pasaste.

La primera vez que le pases los datos los vas a tener todos como undefined porque el useEffect todavia no se ejecuto, vos tenes que pasarle los datos al form despues de que dejen de ser undefined. En settings yo valide eso.

2022-11-03 03:20 UTC, ManuelArzuaga commented
ya estan los cambio pedidos con la validacion de los datos y el bug resuelto
cambia los datos que se piden ingresar(me aparecio conflicto en eso al hacer pull de master, mantuve los cambios que hice por que son los datos que necesita el endpoind de user)

2022-11-05 17:45 UTC, faballay approved these changes
@ManuelArzuaga estoy ok. mergeemos esto que tiene varios dias aca. 
Te agrego una task para agregar un "alert" cuando actualizas los datos de perfil, de que la actualizacion fue exitosa.

2022-11-05 18:06 UTC, billgiberti approved these changes

2022-11-05 18:15 UTC, merged