Web App primer branch
raquevedo/AppArCar pull request #14
Opened 2022-08-31 19:36 UTC by ManuelArzuaga

primer pull request web-app

2022-08-31 21:24 UTC, JJPasso approved these changes

2022-09-01 12:24 UTC, faballay commented
@ManuelArzuaga te dejo unos comentarios simples para corregir 

**Navegacion**

No queda claro que función cumple el botón Inicio, me parece mas natural que solo exista el botón registrarse.
Si la idea es tener un escape hacia la pantalla inicial, lo mejor seria agregarlo en una esquina, algo chico.

En` /registroasociado `
Para mantener un poco la semantica, un asociado es un comercio asociado 
Por lo tanto no deberia tener Nombre, apellido, dni, sino Razon social, Nombre de fantasia.
Falta el numero de celular 

En `/registroestacionamiento`
Similar a asociado, no tenemos nombre y apellido, sino Razon social, nombre de fantasia
La direccion partirla en 2: calle y altura 



La unica duda que me queda es si esto no deberia estar en `fe_dispatcher/web` @raquevedo nos iluminas?

2022-09-06 02:11 UTC, raquevedo commented
tengo entendido que si, aunque todavia no se como va a ser el dispatcher

2022-09-06 14:58 UTC, raquevedo requested changes
Pasemos todo a ingles porfa y despues muevan esto al servicio de frontend que arme

2022-09-10 22:28 UTC, faballay approved these changes

2022-09-10 23:33 UTC, raquevedo requested changes
Quedaron los package.json y package-lock,json en el root del repositorio, porfa miren donde tienen que ir esos archivos o si hay que borrarlos.

Por otro lado dice que no encuentra react-scripts si lo levanto desde donde esta el readme, aca les pego el mensaje de error

> web-app@0.1.0 build
> react-scripts build

sh: 1: react-scripts: not found

Y quedaron un par de cosas sin pasar a ingles tambien

2022-09-12 19:28 UTC, closed without merging