AAC-Web-profile-success-fail-modal-V1
raquevedo/AppArCar pull request #142
Opened 2022-11-06 00:07 UTC by ManuelArzuaga

-creacion de modal para mostrar exito o falla al actualizar el profile
-traduje la frase de home
-bug: en tell about us aparece el modal pero pasa directamente al dashboard no permite hacer click en el modal

2022-11-07 01:53 UTC, ManuelArzuaga commented
@raquevedo este pr tiene tambien los cambios del pr profile update que se mergeo, los cambios que queres hacer los hago aca o creo otro pr con los cambios de profile update????

2022-11-08 00:11 UTC, raquevedo commented
No entiendo, esos cambios estan en master o no?

2022-11-08 00:20 UTC, raquevedo requested changes

2022-11-08 00:20 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Forms/UserForm.js
> +  function modalOn(){
Asi no se maneja el display de un modal, lo podes tener como un hook que define si se ve o no se ve

2022-11-08 00:20 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Forms/UserForm.js
> +    return showModal;
Estas devolviendo siempre true aca, el return no hace nada util.

2022-11-08 00:20 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Forms/UserForm.js
> +        <div class="user-box">
Rompiste la indentacion de todo el jsx

2022-11-08 00:20 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Forms/UserForm.js
> +  const [modalHeader, setModalHeader] = useState('Error');
No veo necesidad de mantener el texto del modal en un hook

2022-11-08 00:20 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Forms/UserForm.js
> +  const [modalBody, setModalBody] = useState('There was an unknown error when processing the request.');
Idem

2022-11-08 00:20 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Forms/UserForm.js
> +    setShowModal(true);
Osea que siempre que mostras el modal el texto pasa a ser el de success? No tiene mucho sentido esto

2022-11-08 00:20 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Forms/UserForm.js
> +    modalOn();
Esta funcion devuelve un boolean, si no lo vas a usar es mejor ni meter un return

2022-11-08 00:20 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Dashboard/DashboardWrapper.js
> +      {isRegistered && UserForm.modalOn === undefined && <Dashboard partnerData={parkingData}/>}
Por que se ve el dashboard solo cuando modalOn es undefined? Si un componente no se renderiza encima del contenido principal de la vista ya no es un modal

2022-11-08 00:20 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Dashboard/DashboardWrapper.js
> +      {isRegistered && UserForm.modalOn === undefined && <Dashboard partnerData={parkingData}/>}
Por otro lado, que pasa si isRegistered es true? No se renderiza ningun componente?

2022-11-09 04:03 UTC, closed without merging