AAC-web-0020-StyleAlerts
raquevedo/AppArCar pull request #143
Opened 2022-11-06 19:34 UTC by JJPasso

estilo en alertas de login, error y caso exitoso

2022-11-08 21:35 UTC, faballay requested changes
@JJPasso 
Nunca pude llegar a la alerta de "Error" cambiaste algo en la logica? 

Por otro lado la alerta de succes hay que emprolijarla
- El boton con la X está de más, cumple la misma funcion de "continue"
- El boton de "continue" no esta centrado
- Las letras que dicen "Account succesfully registered" son muy chicas 
- Hace mas grande el Alert si es necesario. 

![image](https://user-images.githubusercontent.com/16597899/200680206-2db64c77-769d-4ee2-9244-b527104dfab1.png)

2022-11-09 15:47 UTC, raquevedo commented
Yo pude hacer saltar los errores pero no me convencen los estilos, esta mal alineado y el boton circular en el X queda medio mal.

El color de fondo tampoco se usa en ningun lado en el resto del frontend y el texto no tiene nada.

2022-11-09 15:48 UTC, raquevedo requested changes
Creo que hay que mejorar como queda esto.

2022-11-10 22:15 UTC, faballay commented
Me gusta mas como se ve ahora, pero sigue sin estar centrado el boton. 
![image](https://user-images.githubusercontent.com/16597899/201217421-e53e549f-d09a-4882-acce-003634617724.png)

2022-11-11 22:02 UTC, JJPasso commented
![image](https://user-images.githubusercontent.com/51726371/201436879-43cad756-fa09-4c89-9e2d-255f262d643f.png)

2022-11-11 22:03 UTC, JJPasso commented
![image](https://user-images.githubusercontent.com/51726371/201436984-741bdcde-f20a-4d19-af09-0db84dbd37a2.png)

2022-11-19 23:50 UTC, raquevedo commented
Resuelto en AAC-Web-0030

2022-11-19 23:50 UTC, closed without merging