AAC-Web-Links-Navbar-V1
raquevedo/AppArCar pull request #145
Opened 2022-11-07 01:55 UTC by ManuelArzuaga

@raquevedo pr creado para hacer cambios pedidos

2022-11-08 00:10 UTC, raquevedo requested changes

2022-11-08 00:10 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Shared/Navbar.js
> +              <a href = "https://github.com/raquevedo/AppArCar" target="_blank">
Aca el problema es el target="_blank", fijate que el compilador te avisa que es una vulnerabilidad.

2022-11-08 00:10 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Shared/Navbar.js
> +            <li className="text-nav ">
Saca el espacio

2022-11-08 00:10 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Shared/Navbar.js
> +              <a href = "https://www.ucaece.edu.ar/es/" target="_blank">
Aca tambien

2022-11-08 00:10 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Shared/Navbar.js
> +            <li className="text-nav ">
Idem

2022-11-08 21:38 UTC, faballay commented
@ManuelArzuaga esta muy dificil aplicar las correcciones?

2022-11-09 15:44 UTC, raquevedo requested changes
Quedan un par de comentarios sin arreglar. Podes hacer que el fondo del logo de github sea blanco asi es igual que el resto de los iconos?

2022-11-09 15:45 UTC, raquevedo commented
Creo que tambien hay que arreglar donde esta cada cosa y el tamano del icono de github, es muy grande.

Move los 2 iconos y el about us para la derecha

2022-11-11 14:56 UTC, raquevedo commented
Como venimos con esto?

2022-11-19 23:49 UTC, raquevedo commented
Parece que este PR no se termina, ya esta implemetado en el que arme de estilos.

2022-11-19 23:49 UTC, closed without merging