Aac web profile update
raquevedo/AppArCar pull request #149
Opened 2022-11-09 03:58 UTC by ManuelArzuaga

-vuelvo a crear este pr por que el que tiene el modal de success/fail tiene cosas del pr de navbar-link
-este pr ya se habia mergeado, pongan las cosas que hay que cambiar

2022-11-09 04:02 UTC, ManuelArzuaga commented
el pr que tiene el modal success/fail lo elimino fue algo extra de esta semana, lo empece a hacer por que este pr ya se habia mergeado, prefiero corregir estos errores que es una tarea de semanas pasados

2022-11-09 15:38 UTC, raquevedo commented
Los comentarios son los mismos que deje en el otro PR

2022-11-11 14:55 UTC, raquevedo requested changes

2022-11-11 14:55 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Dashboard/DashboardWrapper.js
> +  const [parkingData, setParkingData] = useState({});
Esto lo estas usando para guardar los datos del user, no del parking

2022-11-11 14:55 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Dashboard/DashboardWrapper.js
> +      setParkingData(partner['data'])
setParkingData(user)?

2022-11-11 14:55 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Forms/UserForm.js
> +      name: valuesData['name'],
Que pasa si valuesData es undefined?

2022-11-11 14:55 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Profile/Profile.js
> +    async function assignParkingData() {
assignParkingData pero maneja datos de user

2022-11-11 14:55 UTC, raquevedo commented on frontend_web_service/frontend/src/controllers/usersController.js
> +import {buildHeaders} from './parkingController';
Estas generando una dependencia entre controllers a microservicios diferentes, si tienen que compartir una funcion tiene que ir en un archivo utils que sea independiente.

2022-11-11 14:55 UTC, raquevedo commented on frontend_web_service/frontend/src/controllers/usersController.js
> +  response = await response.json();
Si haces response.json desde el controller perdes la posibilidad de manejar errores. Devolve el response con status desde aca.

2022-11-13 13:29 UTC, closed without merging