AAC-Parking-Service-0010-check-hours
raquevedo/AppArCar pull request #155
Opened 2022-11-12 17:16 UTC by faballay

Agrego la funcion de detectar si el parking esta abierto o cerrado en base a sus horarios configurados

2022-11-12 20:12 UTC, raquevedo requested changes
No me esta funcionando esto

2022-11-12 20:13 UTC, raquevedo commented
{
    "idParking": 1,
    "startMonday": "09:00:00",
    "endMonday": "08:00:00",
    "startTuesday": "21:00:00",
    "endTuesday": "06:00:00.249",
    "startWednesday": "21:00:00",
    "endWednesday": "21:00:00",
    "startThursday": "21:00:00",
    "endThursday": "21:00:00",
    "startFriday": "21:00:00",
    "endFriday": "21:00:00",
    "startSaturday": "21:00:00",
    "endSaturday": "21:00:00",
    "startSunday": "21:00:00",
    "endSunday": "21:00:00",
    "sysCreatedAtDttm": "2022-11-11T15:30:08.000Z",
    "sysUpdatedAtDttm": "2022-11-11T15:30:08.000Z"
}
Esto tiro 204

2022-11-12 21:03 UTC, faballay commented
los patch siempre devuelven 204, igual acordate que con ese endpoint ( 'http://localhost:3003/parking-settings/1' \)  hay que pasarle el datetime :( 

![image](https://user-images.githubusercontent.com/16597899/201494450-a89cb5f8-ef2b-4d18-b50e-d722664178c9.png)

2022-11-13 12:32 UTC, raquevedo approved these changes

2022-11-13 12:32 UTC, merged