AAC-Native-0004-add-styles
raquevedo/AppArCar pull request #25
Opened 2022-09-14 15:22 UTC by JJPasso

nuevos estilos para login y registro en native

2022-09-14 17:42 UTC, raquevedo requested changes
Tenes que armar un objeto stylesheet para poder crear clases de css y definir los estilos desde ahi, modificar todos los tags no es algo que se pueda mantener, no hay forma de hacer cambios a gran escala.

2022-09-14 17:45 UTC, faballay requested changes
La vista desde el browser se rompe
![image](https://user-images.githubusercontent.com/16597899/190225737-088a6e05-cb61-4fe0-bc1e-54a07848aed9.png)

La vista desde el celu tambien tiene errores
![image](https://user-images.githubusercontent.com/16597899/190225849-581b02c6-4b00-4030-a1ba-afa1d7b0a307.png)

2022-09-15 12:15 UTC, faballay approved these changes
Me gustó como quedó, gran laburo. Te envie unos pequeños cambios de estilo, los agrego al backlog. Mergeamos esto

2022-09-17 14:50 UTC, raquevedo approved these changes
Ojo con la indentacion en los archivos, te la arregle en signup.
Fuera de eso esta impecable, muy bueno.

2022-09-19 01:20 UTC, closed without merging