points service basic setup
raquevedo/AppArCar pull request #29
Opened 2022-09-16 03:06 UTC by molle98

Dejé el archivo init vacío para completar, el resto está hecho con los endpoints básicos, para que lo revisen

2022-09-16 12:27 UTC, faballay requested changes
@molle98 antes de revisar el codigo te diria que lo acomodes a la estructura del repo productivo. 
Otro punto grave es que estas subiendo la base de datos `points_database_vol` son un monton de archivos, eso no va. Incluilo en el .gitignore

2022-09-16 12:56 UTC, raquevedo commented
Tampoco la carpeta .vscode, agregala al gitignore asi no la agarra git.
Primero tenes que eliminarla de aca igual.

Por otro lado agrega que el Dockerfile haga la migracion de los modelos a la base de datos asi se puede levantar.

Con esas 2 cosas ya estariamos para mergear.

2022-09-17 13:08 UTC, faballay requested changes
@molle98 bien ahi con los cambios  👍 
Te dejo algunas cosas a revisar con respecto al codigo

2022-09-17 13:08 UTC, faballay commented on points_service/points_service/src/models/driver-benefit.model.ts
> +      columnName: 'driver_id'
El car-driver id no es string

2022-09-17 13:08 UTC, faballay commented on points_service/points_service/src/models/driver-benefit.model.ts
> +      columnName: 'creation_date'
las fechas llevan el sufijo _dt si es date y dttm si es datetime

2022-09-17 13:08 UTC, faballay commented on points_service/points_service/src/models/driver-benefit.model.ts
> +      columnName: 'creation_date'
nose si se deberia llamar fecha de creacion, tal vez es mejor fecha de canje?

2022-09-17 13:08 UTC, faballay commented on points_service/points_service/src/models/driver-benefit.model.ts
> +  constructor(data?: Partial<DriverBenefit>) {
Bueno lo mismo que arriba, falta modelar algunos campos.. Te tomas la tarea de pensarlos? Spoiler: seguro algunos ya te los comente arriba

2022-09-17 13:08 UTC, faballay commented on points_service/points_service/src/repositories/README.md
> +# Repositories
Estos readme.md no aportan nada, seria mejor tener uno a nivel `/points_service`

2022-09-17 13:08 UTC, faballay commented on points_service/points_service/src/__tests__/README.md
> +# Tests
Estos readme.md no aportan nada, seria mejor tener uno a nivel `/points_service`

2022-09-17 13:08 UTC, faballay commented on points_service/points_service/src/controllers/README.md
> +# Controllers
Estos readme.md no aportan nada, seria mejor tener uno a nivel `/points_service`

2022-09-17 13:08 UTC, faballay commented on points_service/points_service/src/datasources/README.md
> +# Datasources
Estos readme.md no aportan nada, seria mejor tener uno a nivel `/points_service`

2022-09-17 13:08 UTC, faballay commented on points_service/docker-compose.yml
> +      POSTGRES_HOST: pointshost
El estandar que venimos manejando es que el HOST sea igual al servicename. Fijate como estan los otros servicios

2022-09-17 23:41 UTC, faballay commented
@molle98 otra cosa a revisar es porque genera un esquema por tabla migrada. Deberia generarlas todas en el mismo esquema, por simplicidad estamos usando public. 

![image](https://user-images.githubusercontent.com/16597899/190879762-a327140e-1036-42f2-824e-d3dd23e19259.png)

2022-09-19 12:28 UTC, raquevedo commented on points_service/points_service/src/models/benefit.model.ts
> +export class Benefit extends Entity {
creo que esto es lo que rompe la migracion tambien

2022-11-08 21:37 UTC, closed without merging