validacion de ingreso de datos primer branch
raquevedo/AppArCar pull request #35
Opened 2022-09-18 01:18 UTC by ManuelArzuaga

2022-09-19 12:21 UTC, raquevedo requested changes

2022-09-19 12:21 UTC, raquevedo commented on frontend_web_service/frontend/package.json
> +    "start": " set PORT=4000 && react-scripts start",
Esto no se tiene que commitear

2022-09-19 12:21 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Login/Login.js
> +      console.log(data);
Para que estamos loggeando esto a consola?
Si queres ver las interacciones con el backend podes mirar los requests desde el navegador.

2022-09-19 12:21 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Login/Login.js
> +  const [password, setPassword] = useState('');
Dejalo como None, no hace falta hacer este cambio

2022-09-19 12:21 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Login/Login.js
> +    if((emailConfirmationL) && (passwordConfirmationL)){
Agrega un mensaje de error cuando esto sea false, sino no hay feedback al usuario de que no salio el login

2022-09-19 12:21 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Login/Login.js
> +  function validationLogin(){
Separa esto en emailValidation y passwordValidation asi son reutilizables, estas mezclando 2 cosas diferentes aca.
Tambien sacalo a otro archivo e importalo asi lo podemos reutilizar desde Register.js

2022-09-19 12:21 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Login/Login.js
> +      alert('Enter an email with the format example@example.com')
No uses popups para avisar que tienen mal los datos, hace que aparezca un warning y que se ponga rojo el campo como se suele user en paginas web.

Un alert es muy intrusivo.

2022-09-19 12:21 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Login/Login.js
> +    if((password != '') && (password.length>=8)){
Verificar que no sea None es mas eficiente

2022-09-19 12:21 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Login/Login.js
> +      alert('Enter a password with 8 digits or more');
Idem

2022-09-19 12:21 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Login/Login.js
> +          <button type="button" class="button" onClick={validationLogin}>Submit</button>
El evento para validar movelo a los campos mismos, onblur te deberia servir

2022-09-19 12:21 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Register/Register.js
> +  }
esta mal indentado esto

2022-09-19 12:21 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Register/Register.js
> +  const [username, setUsername] = useState('');
Idem, dejalo como None

2022-09-19 12:21 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Register/Register.js
> +  const [passwordConfirmationCorrect,setpasswordConfirmationCorrect] = useState(false);
Yo cambiaria esto por passwordMatches

2022-09-19 12:21 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Register/Register.js
> +  const EmailRegex = /\S+@\S+\.\S+/;
Esto importalo desde otro lado, estas duplicando logica

2022-09-19 12:21 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Register/Register.js
> +     if((passwordCorrect == true) && (mailCorrect == true) && (userCorrect == true) && (passwordConfirmationCorrect == true)){
Los if ya estan verificando que los valores sean true, en vez de passwordCorrect == true podes dejar passwordCorrect solo.

Seria: if passwordCorrect && mailCorrect && userCorrect && passwordMatches {}

2022-09-19 12:21 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Register/Register.js
> +      });
Agrega un else que avise que hubo un error

2022-09-19 12:21 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Register/Register.js
> +      alert('Enter a password with 8 digits or more');
Cambia el alert porque se ponga rojo el campo o algo por el estilo

2022-09-19 12:21 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Register/Register.js
> +      alert('Enter an email with the format example@example.com')
Idem

2022-09-19 12:21 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Register/Register.js
> +      alert('Enter a username');
Idem

2022-09-19 12:21 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Register/Register.js
> +      setpasswordCorrect(!passwordCorrect);
por que no seteas un true directamente en vez de poner el valor opuesto?

2022-09-19 12:21 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Register/Register.js
> +      alert('The password to confirm does not match the previous one')
Idem

2022-09-19 12:21 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Register/Register.js
> +          <button type="button" class="button" onClick={Validation}>Submit</button>
Pasa la logica a los campos

2022-09-19 20:29 UTC, raquevedo requested changes

2022-09-19 20:29 UTC, raquevedo commented on frontend_web_service/frontend/package.json
> +    "start": "PORT=4000 react-scripts start",
Perfecto

2022-09-19 20:29 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Login/Login.js
> +import ValidationInputsEmail from '../../utils/ValidationInputsEmail';
Solo los objetos y clases empiezan con mayuscula, funciones tienen la primera palabra minuscula

2022-09-19 20:29 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Login/Login.js
> +  let paswordLenghtL = 0;
Usa un hook aca, lo podes pasar por parametro con el metodo para setearlo

2022-09-19 20:29 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Login/Login.js
> +  console.log(passwordConfirmationL);
Estos logs no deberian estar aca

2022-09-19 20:29 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Login/Login.js
> +return(
Esta mal la indentacion

2022-09-19 20:29 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Login/Login.js
> +          <input type="text" onChange={e => setEmail(e.target.value)} onBlur = {() => {setemailConfirmationL(ValidationInputsEmail(email))}}/>
perfecto esto, podes cambiarle el nombre al metodo a algo tipo validateEmail()?

2022-09-19 20:29 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Login/Login.js
> +          <input type="password" onChange={e => setPassword(e.target.value)} onBlur = {() => {setPasswordConfirmationL(ValidationInputsPassword(password,paswordLenghtL))}}/>
Por que le estas pasando el largo de la contrasena? si ya le pasas el password entonces deberian poder calcularlo dentro de la funcion

2022-09-19 20:29 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Register/Register.js
> +import ValidationInputsPassword from '../../utils/ValidationInputsPassword';
Idem, tienen que empezar con minuscula, ademas podes meter ambas validaciones en un mismo archivo e importar las 2 juntas

2022-09-19 20:29 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Register/Register.js
> +  const [EmailCorrect,setEmailCorrect] = useState(false);
arregla las mayusculas porfa

2022-09-19 20:29 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Register/Register.js
> +     if((PasswordCorrect == true) && (EmailCorrect == true) && (UsernameCorrect == true) && (PasswordConfirmationCorrect == true)){
passwordCorrect == true es lo mismo que solo poner passwordCorrect por ser boolean

2022-09-19 20:29 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Register/Register.js
> +      alert('Missing fields to complete')
Saca este alert, son solo para errores serios y los pueden llegar a bloquear los navegadores.

En vez de eso podes meter un div oculto que cambie a visible cuando se triggerea el else, que sirve de advertencia

2022-09-19 20:29 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Register/Register.js
> +  function ValidateUsername(){
Tiene mal la indentacion, ademas hay que moverla a un util

2022-09-19 20:29 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Register/Register.js
> +  function ValidatePasswordConfirmation(){
Idem

2022-09-19 20:29 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Register/Register.js
> +  function ValidatePasswordConfirmation(){
Tambien estas metiendo funciones dentro de otras funciones

2022-09-19 20:29 UTC, raquevedo commented on frontend_web_service/frontend/src/utils/ValidationInputsEmail.js
> +
Hay muchas lineas en blanco aca, se usa uno entre bloques de logica para separar un poco la funcion y otro entre medio de funciones, nunca tantos seguidos.

2022-09-19 20:29 UTC, raquevedo commented on frontend_web_service/frontend/src/utils/ValidationInputsEmail.js
> +export default ValidationInputsEmail;
export default es solo para modulos, podes exportar una funcion

2022-09-19 20:29 UTC, raquevedo commented on frontend_web_service/frontend/src/utils/ValidationInputsPassword.js
> +export default ValidationInputsPassword;
Idem

2022-09-21 14:19 UTC, raquevedo requested changes

2022-09-21 14:19 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Login/Login.js
> +    if((emailConfirmationL) && (passwordConfirmationL)){
No hacen falta los parentesis

2022-09-21 14:19 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Register/Register.js
> +      <div id={failalert ? 'failalerton' : 'failalertoff'} class="callout alert">
Armate un componente para mensajes de error que solo se renderice si hay un error en el submit.

https://reactjs.org/docs/conditional-rendering.html

{validationError &&
  <ErrorBox message={message}...
}

2022-09-21 14:19 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Register/Register.js
> +          <input id={usernameCorrect ? 'approved' : 'notapproved'} type="text" onChange={e => setUsername(e.target.value)}  onFocus={() =>{setUsernameCorrect(false)}} onBlur = {() =>{setUsernameCorre
Idem

2022-09-21 14:19 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Register/Register.js
> +          <input id={passwordCorrect ? 'approved' : 'notapproved'} type="password" onChange={e => setPassword(e.target.value)} onFocus={() =>{setPasswordCorrect(false)}} onBlur = {() => {ChangePasswo
Idem

2022-09-21 14:19 UTC, raquevedo commented on frontend_web_service/frontend/src/utils/ValidateInputs.js
> +function ValidateEmail(email){
Las funciones van con camelCase, los componentes usan PascalCase

2022-09-21 14:19 UTC, raquevedo commented on frontend_web_service/frontend/src/utils/ValidateInputs.js
> +    if(EmailRegex.test(email)){
return emailRegex.test(email)

El resto no hace falta, la respuesta ya es un boolean.

2022-09-21 14:19 UTC, raquevedo commented on frontend_web_service/frontend/src/utils/ValidateInputs.js
> +    const EmailRegex = /\S+@\S+\.\S+/;
camelCase

2022-09-21 14:19 UTC, raquevedo commented on frontend_web_service/frontend/src/utils/ValidateInputs.js
> +    if ((password != null) && (password.length>=8)){
return ( password && password.length>=8 )

2022-09-21 14:19 UTC, raquevedo commented on frontend_web_service/frontend/src/utils/ValidateInputs.js
> +function ValidatePassword(password){
camelCase

2022-09-21 14:19 UTC, raquevedo commented on frontend_web_service/frontend/src/utils/ValidateInputs.js
> +function ValidatePasswordConfirmation(password,passwordConfirmation){
camelCase y separa los parametros con un espacio despues de la coma

2022-09-21 14:19 UTC, raquevedo commented on frontend_web_service/frontend/src/utils/ValidateInputs.js
> +    if((password == passwordConfirmation) && (passwordConfirmation.length>=8)){
return ((password == passwordConfirmation) && (passwordConfirmation.length >= 8))

2022-09-21 14:19 UTC, raquevedo commented on frontend_web_service/frontend/src/utils/ValidateInputs.js
> +export {ValidateEmail,ValidatePassword,ValidatePasswordConfirmation,ValidateUsername};
export { ValidateEmail, ValidatePassword, ValidatePasswordConfirmation, ValidateUsername };

2022-09-21 15:00 UTC, raquevedo commented
Tenes conflictos tambien

2022-09-21 22:48 UTC, ManuelArzuaga commented on frontend_web_service/frontend/src/components/Login/Login.js
> +    if((emailConfirmationL) && (passwordConfirmationL)){
sin los parentesis me tira error

2022-09-21 23:13 UTC, raquevedo requested changes

2022-09-21 23:13 UTC, raquevedo commented on frontend_web_service/frontend/src/components/App/App.css
> +#notapproved{
Unos ultimos cambios, en css la nomenclatura es not-approved

2022-09-21 23:13 UTC, raquevedo commented on frontend_web_service/frontend/src/utils/AlertFail.js
> +function alertFail(failalert){
Hay que moverlo a la carpeta de componentes, pero eso veamoslo dentro de otro PR, ya seria armar el componente de alerta

2022-09-21 23:13 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Register/Register.js
> +          <input id={emailCorrect ? 'approved' : 'notapproved'} type="text" onChange={e => setEmail(e.target.value)} onFocus={() =>{setEmailCorrect(false)}} onBlur = {() => {setEmailCorrect(validateE
Los onFocus estan haciendo que todo el texto se ponga rojo hasta que cumpla la condicion, no valides hasta que no deja el campo el usuario

2022-09-22 12:20 UTC, raquevedo requested changes

2022-09-22 12:20 UTC, raquevedo commented on frontend_web_service/frontend/src/components/App/App.css
>  #failalertoff{
las otras tambien porfa

2022-09-22 12:20 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Login/Login.js
> +          <input id={isPasswordValid ? 'approved' : 'not-approved'} type="password" onChange={e => setPassword(e.target.value)} onKeyUp={() => {setIsPasswordValid(validatePassword(password))}}/>
Seguimos teniendo el mismo problema de que te pone todo el texto rojo

2022-09-22 12:20 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Register/Register.js
> +import {alertFail} from '../../components/AlertFail/AlertFail';
Si lo vas a convertir en un componente entonces hay que modificarlo un poco para que sea uno

2022-09-23 12:08 UTC, faballay commented on frontend_web_service/frontend/src/utils/ValidateInputs.js
> +function ValidatePasswordConfirmation(password,passwordConfirmation){
@ManuelArzuaga se entiende lo que es camelCase?

2022-09-24 22:43 UTC, raquevedo commented on frontend_web_service/frontend/src/components/App/App.css
>  #failalertoff{
falta esto Manu

2022-09-24 22:44 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Login/Login.js
> +        failalert = {failalertL}
failAlert

2022-09-24 22:45 UTC, raquevedo commented on frontend_web_service/frontend/src/utils/ValidateInputs.js
> +    if((password == passwordConfirmation) && (passwordConfirmation.length>=8)){
Agrega unos espacios entre length, >= y el 8

2022-10-01 13:35 UTC, raquevedo commented
Vas a terminar este PR? Lo agarro yo sino

2022-10-01 20:55 UTC, raquevedo requested changes

2022-10-01 20:55 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Register/Register.js
> +          <input className='emailregister' type="text" onChange={e => setEmail(e.target.value)} onFocus = {() => document.getElementsByClassName('emailregister')[0].id = 'typing'} onBlur = {() => val
Todas estas clases hacen algo? faltaria ponerles bien el nombre tipo email-register

2022-10-02 13:19 UTC, raquevedo approved these changes

2022-10-03 01:49 UTC, faballay approved these changes

2022-10-03 01:49 UTC, faballay commented
Cerremos esto please

2022-10-03 03:05 UTC, merged