integracion de estilos en master. Vista Login Vista Sign Up
raquevedo/AppArCar pull request #38
Opened 2022-09-19 21:08 UTC by JJPasso

2022-09-19 23:10 UTC, raquevedo requested changes

2022-09-19 23:10 UTC, raquevedo commented on mobileClient/Login/components/registry.js
> +                    <Text  style={{fontSize: 12,justifyContent: 'center',alignItems: 'center',color: '#ffffff'}} onPress={showDatePicker}>Fecha de Nacimiento</Text>
Tenes muchas cosas de style aca, yo lo meteria en una clase, hay un espacio de mas entre Text y style

2022-09-19 23:10 UTC, raquevedo commented on mobileClient/Login/components/registry.js
> +import { View, Button,Text,Image} from 'react-native';
Agrega espacios entre valor y al final, queda mas limpio

2022-09-19 23:10 UTC, raquevedo commented on mobileClient/Login/components/registry.js
> +                  </LinearGradient>
Arregla la indentacion porfa, 2 espacios por nivel

2022-09-19 23:10 UTC, raquevedo commented on mobileClient/Login/components/signin.js
> +import { View, Button, Text, StyleSheet,Image} from 'react-native';
Idem, espacios

2022-09-19 23:10 UTC, raquevedo commented on mobileClient/Login/components/signin.js
> +import {LinearGradient} from 'expo-linear-gradient';
Idem

2022-09-19 23:10 UTC, raquevedo commented on mobileClient/Login/components/signin.js
> +        </LinearGradient>
Indentacion

2022-09-19 23:10 UTC, raquevedo commented on mobileClient/Login/components/signin.js
> +                  <View style={{flex: 1,justifyContent: 'center',alignItems: 'center'}}></View>
esto va en una clase

2022-09-19 23:10 UTC, raquevedo commented on mobileClient/Login/components/signin.js
> +                <View style={{flex: 1,justifyContent: 'center',alignItems: 'center'}}></View>
Es la misma logica que abajo, metelo en una clase para no duplicar logica

2022-09-19 23:10 UTC, raquevedo commented on mobileClient/Services/styles.js
> +  export default styles;
Arregla la identacion

2022-09-19 23:10 UTC, raquevedo commented on mobileClient/SignUp/components/signup.js
> +          <View style={{flex: 1,justifyContent: 'center',alignItems: 'center'}}></View>
Denuevo la misma logica, arma la clase asi dejamos todo igual

2022-09-19 23:10 UTC, raquevedo commented on mobileClient/makeIpFile.js
> +ip_address = "192.168.0.34";
no hardcodees el IP, sino no nos va a funcionar al resto

2022-09-20 13:06 UTC, JJPasso commented on mobileClient/makeIpFile.js
> +ip_address = "192.168.0.34";
no me esta funcionando ese script, lo puedo poner en gitignore?

2022-09-20 13:25 UTC, faballay commented on mobileClient/makeIpFile.js
> +ip_address = "192.168.0.34";
@billgiberti No funciona en Windows, hay que ver si se puede arreglar el script en el proximo sprint. Por ahora saca el archivo de tu commit y listo.

2022-09-20 13:36 UTC, JJPasso commented on mobileClient/makeIpFile.js
> +ip_address = "192.168.0.34";
como hago eso? pasame los comandos para sacarlo

2022-09-20 13:38 UTC, faballay commented on mobileClient/makeIpFile.js
> +ip_address = "192.168.0.34";
dejalo como esta en master, borra esa linea que hardcodeaste tu ip

2022-09-20 20:13 UTC, raquevedo requested changes

2022-09-20 20:13 UTC, raquevedo commented on mobileClient/Login/components/registry.js
> +  const [isDatePickerVisible, setDatePickerVisibility] = React.useState(false);
el nombre de la funcion setDatePickerVisibility tiene que ser setIsDatePickerVisible, siempre el nombre de la variable con set al principio

2022-09-20 20:13 UTC, raquevedo commented on mobileClient/Login/components/registry.js
> +            style={styles.containbuttonstylel}
Usa camelCase para los nombres de clases porfa, es estandar

2022-09-21 13:09 UTC, raquevedo approved these changes

2022-09-21 14:37 UTC, faballay approved these changes

2022-09-21 18:10 UTC, merged