Aac web parking dashboard 0002 basic setup
raquevedo/AppArCar pull request #46
Opened 2022-09-29 17:44 UTC by molle98

Cambios de dashboard adaptandolo a foundation

2022-09-30 13:28 UTC, raquevedo requested changes
Ya casi esta

2022-09-30 13:28 UTC, raquevedo commented on frontend_web_service/frontend/assets/css/Dashboard.css
> +}
Elimina esto

2022-09-30 13:28 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Dashboard/ParkingHeader.js
> +function ParkingHeader(props){
Podemos cambiarle el nombre a TextCard? Es super generico

2022-09-30 14:28 UTC, raquevedo approved these changes

2022-10-01 15:05 UTC, raquevedo requested changes
Estas subiendo los commits de tu issue nuevo a este PR!!

2022-10-01 16:01 UTC, raquevedo approved these changes

2022-10-01 16:21 UTC, faballay approved these changes

2022-10-01 16:33 UTC, merged