Aac parking service 0001 setup
raquevedo/AppArCar pull request #49
Opened 2022-10-02 12:09 UTC by faballay

**Resumen**
- Setup base de datos 
- Setup del microservicio
- Config Kong y Docker-compose principal 
- Auth via Token 
- Endpoints iniciales de Parking 

**TODO**
- Utilizar el servicio de coordenadas para calcular lat:lon

#### Ms Parking 

Detallo los endpoints que cambian un poco respecto a lo que venimos haciendo para evitar confusiones...

-Crear un parking POST `/parking/create` 
**officeHour** es JSON ojo ahi 
```
curl -X 'POST' \
  'http://localhost:3003/parking/create' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2NjMxMjcwNjciLCJuYW1lIjoiTWF4aW1pbGlhbm8gIiwiZW1haWwiOiJtYXhpbWlsaWFubzEuZ2lsYmVydG9AZ21haWwuY29tIiwiaWF0IjoxNjYzMTI5ODM2LCJleHAiOjE2NjMxNTE0MzZ9.eN3w--3foee7O_mHtMz2WtY13P2wvhQRWnKdDC-hAf0' \
  -H 'Content-Type: application/json' \
  -d '{
  "businessName": "string",
  "cuitNumber": "string",
  "streetName": "string",
  "streetNumber": 0,
  "qtyTotalSlots": 0,
  "officeHours": "{}",
  "priceHour": 0,
  "price_6Hours": 0,
  "price_12Hours": 0,
  "price_24Hours": 0,
  "priceWeek": 0,
  "priceMonth": 0
}'
```

- Actualizar un parking PATCH `/parking/update/{id}`
- Obtener info de un parking GET `/parking/{id}`
- Eliminar un parking DELETE `/parking/{id}`

**CLAVE para el dashboard** @molle98 

- Obtener todos los parkings asociados a un usuario GET `/parking`

`curl -X 'GET' \
  'http://localhost:3003/parking' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2NjMxMjcwNjciLCJuYW1lIjoiTWF4aW1pbGlhbm8gIiwiZW1haWwiOiJtYXhpbWlsaWFubzEuZ2lsYmVydG9AZ21haWwuY29tIiwiaWF0IjoxNjYzMTI5ODM2LCJleHAiOjE2NjMxNTE0MzZ9.eN3w--3foee7O_mHtMz2WtY13P2wvhQRWnKdDC-hAf0'`

Te devuelve una lista con todos los parkings y el status 
list{ parkingInfo;  status }

Ejemplo 
```

[
  {
    "parkingInfo": {
      "id": 1,
      "businessName": "miprimerpark",
      "cuitNumber": "stri123213g",
      "streetName": "string",
      "streetNumber": 0,
      "geocode": {
        "latitude": 0,
        "longitude": 0
      },
      "qtyTotalSlots": 0,
      "officeHours": {},
      "priceHour": 0,
      "price_6Hours": 0,
      "price_12Hours": 0,
      "price_24Hours": 0,
      "priceWeek": 0,
      "priceMonth": 0,
      "sysCreatedAtDttm": "2022-10-02T11:50:50.000Z",
      "sysUpdatedAtDttm": "2022-10-02T11:50:50.000Z"
    },
    "status": {
      "idParking": 1,
      "status": "active",
      "officeHours": {},
      "qtyTotalSlots": 0,
      "qtyFreeSlots": 0,
      "qtyBussySlots": 0,
      "qtyReservedSlots": 0,
      "qtyBlockedSlots": 0,
      "sysCreatedAtDttm": "2022-10-02T11:50:51.000Z",
      "sysUpdatedAtDttm": "2022-10-02T11:50:51.000Z"
    }
  },
  {
    "parkingInfo": {
      "id": 2,
      "businessName": "string",
      "cuitNumber": "string",
      "streetName": "string",
      "streetNumber": 0,
      "geocode": {
        "latitude": 0,
        "longitude": 0
      },
      "qtyTotalSlots": 0,
      "officeHours": {},
      "priceHour": 0,
      "price_6Hours": 0,
      "price_12Hours": 0,
      "price_24Hours": 0,
      "priceWeek": 0,
      "priceMonth": 0,
      "sysCreatedAtDttm": "2022-10-02T11:55:21.000Z",
      "sysUpdatedAtDttm": "2022-10-02T11:55:21.000Z"
    },
    "status": {
      "idParking": 2,
      "status": "active",
      "officeHours": {},
      "qtyTotalSlots": 0,
      "qtyFreeSlots": 0,
      "qtyBussySlots": 0,
      "qtyReservedSlots": 0,
      "qtyBlockedSlots": 0,
      "sysCreatedAtDttm": "2022-10-02T11:55:21.000Z",
      "sysUpdatedAtDttm": "2022-10-02T11:55:21.000Z"
    }
  }
]
```

2022-10-02 13:17 UTC, raquevedo requested changes

2022-10-02 13:17 UTC, raquevedo commented on .gitignore
> +parking_service/parking_database_vol/*
Estuve tocando el gitignore y esto no funciona, tenes que meter parking_database_vol de una o intenta meter la carpeta root sin tener permisos

2022-10-02 13:17 UTC, raquevedo commented on parking_service/db/scripts/init_parking_db.sql
> +    office_hours json,
No armemos JSONs dentro de la base de datos, matengamosla normalizada. De ultima arma una tabla aparte para estos valores compuestos.

2022-10-02 13:17 UTC, raquevedo commented on parking_service/docker-compose.yml
> +# parking_service:
Esta bien que este comentado todo esto?

2022-10-02 13:17 UTC, raquevedo commented on parking_service/parking_service/.vscode/launch.json
> +{
Subiste tus archivos de configuracion de vscode

2022-10-03 23:20 UTC, faballay commented on parking_service/parking_service/.vscode/launch.json
> +{
Gracias ya los saque

2022-10-03 23:22 UTC, faballay commented on parking_service/docker-compose.yml
> +# parking_service:
Ahi lo deje actualizado para dev. La verdad ni lo uso ese compose, solo para levantarme la db.

2022-10-03 23:22 UTC, faballay commented on parking_service/db/scripts/init_parking_db.sql
> +    office_hours json,
Listo!!

2022-10-03 23:22 UTC, faballay commented on .gitignore
> +parking_service/parking_database_vol/*
Ahi vi como quedó en master y lo cambie.

2022-10-04 12:33 UTC, raquevedo approved these changes

2022-10-05 20:52 UTC, billgiberti approved these changes

2022-10-05 21:06 UTC, merged