AAC-0012-style-web
raquevedo/AppArCar pull request #57
Opened 2022-10-10 18:49 UTC by JJPasso

Para este PR: 
* estilos en pantalla de inicio
* estilos en login y register
* estilos el dashboard a medias (a la espera del pr de marcos)

2022-10-10 22:12 UTC, faballay requested changes
Esta bueno el home con video, pero pusiste una descripcion de pr que no se condice con el codigo que hay publicado.

2022-10-10 22:44 UTC, raquevedo requested changes
Queda muy bien el home pero es lo unico que hay. Fijate que paso con el navbar, login, dashboard, etc. Segun el PR son parte del branch.

2022-10-11 02:04 UTC, raquevedo commented
Ya va a ser martes y todavia no tenemos PR para revisar, metele porfa que despues no nos dejas tiempo para revisarlo.

2022-10-19 13:28 UTC, raquevedo commented on frontend_web_service/frontend/src/components/SignIn/SignIn.js
> +            <div className="cell medium-6 small-12">
Me parece que vamos a tener que cambiar estos a className="cell large-6 medium-12"

No estan escalando bien a pantallas intermedias.

2022-10-19 13:29 UTC, raquevedo commented
@JJPasso Estamos a 2 semanas de que abriste este PR, el codigo del front esta cambiando mucho y estas re desactualizado.

Por que no mergeamos todavia el home y la pantalla de login? Estas metiendo el css entero en un solo PR?

Ojo porque cada vez hay mas conflictos.

2022-10-19 13:37 UTC, JJPasso commented on frontend_web_service/frontend/src/components/SignIn/SignIn.js
> +            <div className="cell medium-6 small-12">
Dale

2022-10-19 13:41 UTC, JJPasso commented
voy a cerrar este pr y voy a subir uno nuevo con el master actual así resuelvo los conflictos. y mergeamos rapido con el home y login register con su estilos.

2022-10-19 13:41 UTC, JJPasso commented
ahora a la tarde lo subo

2022-10-19 19:13 UTC, closed without merging