Aac-web-0012-dynamic-parking-urls
raquevedo/AppArCar pull request #60
Opened 2022-10-14 14:13 UTC by raquevedo

2022-10-14 14:56 UTC, billgiberti approved these changes

2022-10-14 19:11 UTC, JJPasso requested changes
hay problemas con el formulario de profile, tiene que aparece una sola vez y cada vez que lo completo y me voy a profile aparece vacio. refresco dashboard y me vuelve a aparecer

2022-10-14 19:45 UTC, raquevedo commented
El boton de manage te tiene que llevar a una pagina donde solo se ve el ID del garage, si la pagina se pone blanca con un numero esta bien.

2022-10-14 19:49 UTC, JJPasso commented
en mi caso el botón de manage no reacciona :(

2022-10-14 20:10 UTC, molle98 submitted a review, later dismissed

2022-10-14 20:19 UTC, faballay requested changes
@raquevedo agrego algunos comments, entiendo que algunas correcciones pueden ameritar otro pr con esos cambios, manejalo vos. 

- Cuando apreto en el boton Add Parking  aparece el texto **NEW PARKING GARAGE**  No es redudante ? Alcanza con solo poner Parking? No habiamos deprecado la palabra **GARAGE** @billgiberti ? 



- Si desde el dashboard, uso el side-bar para ir a **Profile**, me aparecen los campos en blanco seria bueno igual que la parte mobile, que autocomplete con los valores actuales. 


- Si desde el dashboard apreto en AppArCar (NavBar) me manda a una pantalla donde tengo el boton "login", si apreto "login" vuelvo al dashboard. Medio raro ese comportamiento. @billgiberti @JJPasso @molle98 


- Lo que hay que modificar es el form de Profile, esta usando el endpoint de partners y deberia usar el de parking_users. No tiene sentido que una persona física tenga Business Name. Este cambio tal vez en otro pr.  

- El boton de Manage, no me envia a ningun lado por ahora. 


- A tener en cuenta, o sumar al backlog: alguna ruedita de "cargando" cuando hacemos las request, ya sea add parking, o register, porque a veces queda la sensacion que "no esta pasando nada" o "esta colgado". @JJPasso @billgiberti @molle98

2022-10-14 20:19 UTC, faballay commented on frontend_web_service/frontend/src/components/Management/GarageBoard.js
> +export default function GarageBoard() {
Cual seria la diferencia entre ParkingContainer y GarageContainer? 
Creo que para no generar confusion habiamos deprecado la palabra Garage, se puede cambiar por otra ?

2022-10-14 20:19 UTC, faballay commented on frontend_web_service/frontend/src/components/Dashboard/ParkingAccordionContent.js
> +          Available slots: {props.garage.status.qtyBussySlots}
Este label quedó con error, seria Bussy Slots en vez de Available slots

2022-10-14 21:26 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Dashboard/ParkingAccordionContent.js
> +          Available slots: {props.garage.status.qtyBussySlots}
Busy se escribe con una s, lo podemos arreglar en back o es mucho quilombo?

2022-10-14 21:27 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/GarageBoard.js
> +export default function GarageBoard() {
Esta seria la vista de un garage especifico, lo meti aca para que Marcos tenga armado el routing.

2022-10-14 21:29 UTC, raquevedo commented
Ahi van los cambios para lo que tiene que ver con este PR, el resto lo tengo en mente ya, lo voy a ir cambiando estos dias a medida que pueda, pero primero tengo que hacer lo de Notification service

2022-10-15 16:44 UTC, faballay commented on frontend_web_service/frontend/src/components/Dashboard/ParkingAccordionContent.js
> +          Available slots: {props.garage.status.qtyBussySlots}
De pedo vi este msj, si de una. ahi lo anoto

2022-10-17 12:06 UTC, faballay approved these changes
Me lleve algunos comentarios pendientes al backlog. Cerremos esta version 👍

2022-10-18 03:58 UTC, JJPasso reviewed
No hay visibilidad en este pr de los cambios pendientes del mismo, nose si esta pendiente lo de profile pero sigue estando el problema de no se guarda la informacion del profile y en cada refresh de dashboard salta el formulario. en Cuanto a Manage funciona. Esta costando bastante tiempo en crearse los accordions en el botón de add parking en mi caso.

2022-10-18 03:59 UTC, JJPasso approved these changes

2022-10-18 04:44 UTC, ManuelArzuaga approved these changes

2022-10-18 12:35 UTC, merged