AAC-native-0011-fix-feedback-styles
raquevedo/AppArCar pull request #65
Opened 2022-10-15 04:24 UTC by JJPasso

Este PR contiene las correcciones pendientes a corregir del release 1.

Se agrego estilos al boton Patent

2022-10-15 16:39 UTC, faballay requested changes
@JJPasso bien con los cambios, algunas cosas generales a mejorar para los proximos prs. 
- Usa los labels de github, para etiquetar tu pr, te los agrego yo esta vez.
- Aprovecha la descripción del pr para decir lo que hace, 

Este PR contiene las correcciones pendientes a corregir del release 1. ⚠️ 
Cuales son esas correcciones? **Pasaron 3 semanas del release 1**, imposible que todos las recordemos. 

Se agrego estilos al boton Patent 🆗 

- Cuando resuelvas estos comentarios, por favor aclara que estas resolviendo para poder volver a probar. 
- Si consideras que algo esta fuera del scope de este PR, agregalo al backlog y ponele una fecha. 


#### Profile - Registro
- Hay un comportamiento extraño en el formulario que se completa por única vez en el registro. 
El combo de "seleccione genero", cuando seleccionas un genero no te lo muestra, tenes que seleccionarlo 2 veces el mismo genero para que te lo refleje.
- El calendario para seleccionar fecha me aparece todo en blanco
![calendario](https://user-images.githubusercontent.com/16597899/195997942-0c98f1d8-e093-4963-83b1-4f2a3e629c15.jpeg)
![profile](https://user-images.githubusercontent.com/16597899/195997949-9e1ceb71-f512-4cd2-b794-5084eaeac7b6.jpeg)

#### Botón de patente 
- Si el usuario no tiene auto, que muestre "add car" y te mande a la parte de agregar auto
- Si el usuario tiene autos que diga "select car" en vez de "select patent". Este punto es bastante simple pero capaz @billgiberti te puede ayudar si te bloqueas.
- Las letras de la patente no se renderizan bien, quedan cortadas
- El listado que se despliega con los autos a elegir, hay que mejorarlo es muy dificil seleccionar 1 auto, estan muy pegados. 
![patente](https://user-images.githubusercontent.com/16597899/195997937-4607da4e-3f14-45ec-b6c2-d6bf23371559.jpeg)

#### Cars 
- 1 de las correcciones era mantener el logo de la marca en todas las pantallas, bueno cuando vas a editar los datos de un auto, en esa pantalla falta la marca Apparcar.

2022-10-17 03:22 UTC, JJPasso commented
@faballay consulta fede tu celu es android o iphone?

2022-10-17 12:09 UTC, faballay commented
@JJPasso iphone

2022-10-18 13:12 UTC, JJPasso commented
@faballay 
Se resolvió el botón de patent.
Se resolvió el fix de el input genero.
Se agregaron las imagenes de appcar que faltaban.

2022-10-19 22:49 UTC, molle98 approved these changes

2022-10-19 22:52 UTC, billgiberti approved these changes

2022-10-19 22:53 UTC, merged