Basic management dashboard setup and hour component
raquevedo/AppArCar pull request #70
Opened 2022-10-15 23:26 UTC by molle98

Copio de anterior branch comentario:

Cambios realizados:

-Esqueleto principal de componente de tabs (Garage Board) en path de "manage/:id", con sus respectivos tabs de Notifications,
Hours, Settings y Status. Cada tab posee ya su propio estado, al cambiar de tab en tab cambiamos el contenido.

-Componente de tabla de horarios en Hours tab, para poder setear los horarios de Lunes a Domingos. Necesita aún poder guardar el estado del seteo de horarios.

2022-10-16 23:55 UTC, faballay commented
No me queda claro, que pr es el que vale? Este o https://github.com/raquevedo/AppArCar/pull/67 ?

2022-10-17 00:08 UTC, raquevedo commented
Idem, no entiendo, el otro hay que cancelarlo?

2022-10-17 01:05 UTC, molle98 commented
claro, este es el PR que vale, el otro habria que cancelarlo

2022-10-17 12:52 UTC, raquevedo requested changes
Esto no buildea con las dependencias actuales, algunos paquetes piden react 16

2022-10-18 18:50 UTC, closed without merging