inicio de proyecto web prueba
raquevedo/AppArCar pull request #9
Opened 2022-07-08 18:04 UTC by JJPasso

2022-07-08 18:04 UTC, JJPasso commented
inicio de proyecto react prueba de branch

2022-07-09 14:43 UTC, faballay approved these changes
Excelente @JJPasso, te comenté algo mínimo en el readme. 

Por si a alguien le pasa, tuve que instalar esto para que me funcione:
`npm install react-scripts --save`



El resto OK

2022-07-09 14:43 UTC, faballay commented on fe_dispatcher/web/README.md
> +In the project directory, you can run:
Acá podes aclarar al directorio?  En este caso fe_dispatcher/web

2022-07-10 14:19 UTC, raquevedo approved these changes
Buenisimo Juan!

2022-08-29 20:00 UTC, raquevedo requested changes
Cuidado que estas subiendo binarios pesados y archivos temporales

2022-08-31 21:40 UTC, closed without merging