Aac-web-aboutus-finished
raquevedo/AppArCar pull request #94
Opened 2022-10-21 03:33 UTC by ManuelArzuaga

Cree un nuevo PR porque tenia mezclado cosas de otros PRs

2022-10-22 22:22 UTC, raquevedo requested changes
Lo veo bien por ahora pero hacen falta un par de cosas mas

- La indentacion en los archivos esta mal, acordate que usamos 2 espacios para indentar, revisa todos los cambios que agregaste.
- El path esta bien, se puede acceder a la pagina pero no hay desde donde hacerlo en el front. Agrega un link al aboutus en la barra de navegacion que tenemos arriba de la pagina.
- El contenido de la pagina habria que completarlo tambien en vez de poner un placeholder, yo pondria titulos de laburo, roles dentro del proyecto y el nombre de  la carrera, como un mini CV.

2022-10-22 22:23 UTC, raquevedo commented
Fijate tambien que tenes varios warnings en la consola, mas que nada variables no utilizadas

2022-10-22 23:16 UTC, ManuelArzuaga commented
el contenido de la pagina yo pensaba que cada uno ponga sus conclusiones del tp, dificultades, aprendizaaje @raquevedo

2022-10-23 23:12 UTC, faballay approved these changes

2022-10-24 12:16 UTC, raquevedo approved these changes

2022-10-24 12:16 UTC, merged