Aac web status tab basic setup
raquevedo/AppArCar pull request #95
Opened 2022-10-21 06:42 UTC by molle98

Listo el status tab. Trae todos los datos del parking por ID de cada uno

2022-10-21 16:02 UTC, faballay commented
@molle98 @raquevedo 

Estas haciendo 1 get a la API por cada atributo que queres mostrar en al frontend? 
No entiendo porque haces eso, si con 1 solo get ya tenes el status de todo.. 
No se puede hacer de otra forma? O estoy leyendo mal el codigo yo?

2022-10-21 16:35 UTC, faballay requested changes

2022-10-21 16:35 UTC, faballay commented on frontend_web_service/frontend/src/components/Management/OccupiedSlots.js
> +              {totalSlots.qtyBussySlots}
Esto esta mal, no se llama asi el campo.

2022-10-21 17:06 UTC, billgiberti commented
> @molle98 @raquevedo
> 
> Estas haciendo 1 get a la API por cada atributo que queres mostrar en al frontend? No entiendo porque haces eso, si con 1 solo get ya tenes el status de todo.. No se puede hacer de otra forma? O estoy leyendo mal el codigo yo?

2022-10-21 17:12 UTC, billgiberti commented
Marcos fijate de encararlo por este lado.

En ManagmentBoardJs las instancias a sub componentes deberían hacerse con las variables con referencia a los estados que te agrego del siguiente modo:

    const [totalSlots, setTotalSlots] = useState([]);
    const [availableSlots, setAvailableSlots] = useState([]);
    const [accupiedSlots, setOccupiedSlots] = useState([]);
    const [aookedSlots, setBookedSlots] = useState([]);
    const [alockedSlots, setBlockedSlots] = useState([]);

    useEffect(() => {
        fetchData();
    }, []);

    const fetchData = async () => {
        const data = await getParkingDataID(params.id)
        setTotalSlots(data."aca nombre real del atributo");
        setAvailableSlots(data."aca nombre real del atributo");
        setOccupiedSlots(data."aca nombre real del atributo");
        setBookedSlots(data."aca nombre real del atributo");
        setBlockedSlots(data."aca nombre real del atributo");
    }

    <div>
  	  <TotalSlots totalSlots={totalSlots}/>
          <AvailableSlots totalSlots={availableSlots}/>
          <OccupiedSlots totalSlots={accupiedSlots}/>
          <BookedSlots totalSlots={aookedSlots}/>
          <BlockedSlots totalSlots={alockedSlots}/>
    </div>   

_El useEffect y la definicion de la función que se llama adentro lo dejaría de este lado y lo borraría de los subcomponentes.
_Los nombres en los export de los sub componentes deberían llamarse igual que los que estas poniendo en las instancias  en este código
ejemplo:

si instancias <OccupiedSlots totalSlots={accupiedSlots}/> el sub componente debería exportar del siguiente modo:

export default function OccupiedSlots

2022-10-21 17:17 UTC, billgiberti commented
Otro tema:

así como está puesto solo actualizará datos en el primer renderizado.

El useEffect tiene tres modos de uso dependiendo del segundo param q se le pasa. 
sin arreglo -> se ejecuta cada vez que cambie cualquier cosa de la vista.
con arreglo vacío -> se ejecuta solo en el primer render.
con arreglo con variables como por ejemplo estados -> ejecuta cada vez que esas variables se actualizan, es decir se lo hace escuchar esas variables.

2022-10-21 17:37 UTC, raquevedo requested changes
Tenes que hacer muchos cambios, fijate de pedir los datos una unica vez y dejar de repetir logica en los componentes.

Para los cards necesitas un solo componente, no uno por tipo de dato.

2022-10-21 17:37 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Dashboard/ParkingList.js
> +export const Button = styled.button`
Por que estas exportando un boton desde un archivo de un componente?

2022-10-21 17:37 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/AvailableSlots.js
> +    const data = await getParkingDataID(params.id)
Si no metes esto en un useEffect se va a correr con cada render

2022-10-21 17:37 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/AvailableSlots.js
> +          </Typography>
Esta mal la indentacion aca

2022-10-21 17:37 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/BlockedSlots.js
> +  const fetchData = async () => {
Idem, useEffect

2022-10-21 17:37 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/BlockedSlots.js
> +            <div className='custom-parkingcard'>
Idem, indentacion

2022-10-21 17:37 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/BookedSlots.js
> +    const data = await getParkingDataID(params.id)
Idem

2022-10-21 17:37 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/BookedSlots.js
> +          </Typography>
Idem

2022-10-21 17:37 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/BookedSlots.js
> +          Booked Slots:
Esto dice Booked slots en vez de total slots

2022-10-21 17:37 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/OccupiedSlots.js
> +export default function TotalSlots() {
Estas repitiendo la logica de los cards para cada dato en vez de pasarla por parametros, por eso estas haciendo un llamado por dato.

2022-10-21 17:37 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/OccupiedSlots.js
> +  useEffect(() => {
Este useEffect no tiene una lista de eventos, va a correr con cada render.

2022-10-21 17:37 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/OccupiedSlots.js
> +    <Card variant='outlined' sx={{ width: 2000, m: 3 }}>
Usa un grid en vez de width

2022-10-21 17:37 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/TotalSlots.js
> +export default function TotalSlots() {
Idem, repetis la logica del mismo componente

2022-10-21 17:37 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/TotalSlots.js
> +  }, []);
Aca si esta bien hecho el useEffect

2022-10-21 17:41 UTC, raquevedo commented on frontend_web_service/frontend/src/controllers/parkingController.js
> +  return await data.json();
Otra cosa, si vos devolves solo el body del request no podes revisar el status y manejar errores. Devolve el data como viene del fetch de una asi despues podes ver el .json() y .status()

2022-10-21 17:44 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/TextCards.js
> +    }, [params.id]);
params.id viene del url y nunca cambia. Lo que queres hacer aca es que el llamado se haga una sola vez, la lista vacia estaba bien.

2022-10-21 17:46 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/TextCards.js
> +        const data = await getParkingDataID(params.id)
Despues se recibir el dato tenes que validar el status del request, por eso te digo que es mejor devolver el response entero desde el controller.

if (response.status === 200) {
  const data = await response.json()
} else {
  console.log( mensaje de error )
}

2022-10-21 17:47 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/TextCards.js
>                          <div className='custom-parkingcard'>
Esto va adentro de un componente, no de un div. Lo que hiciste no fue reutilizar el componente, solo copiaste el codigo en el componente padre que tenia.

2022-10-21 19:08 UTC, molle98 commented on frontend_web_service/frontend/src/components/Management/OccupiedSlots.js
> +              {totalSlots.qtyBussySlots}
decis qtyBussySlots?

2022-10-21 19:16 UTC, faballay commented on frontend_web_service/frontend/src/components/Management/OccupiedSlots.js
> +              {totalSlots.qtyBussySlots}
Yes, fijate como está en master.

2022-10-21 19:39 UTC, molle98 commented on frontend_web_service/frontend/src/components/Management/OccupiedSlots.js
> +              {totalSlots.qtyBussySlots}
es modificarle una S a Bussy no?

2022-10-21 19:43 UTC, faballay commented on frontend_web_service/frontend/src/components/Management/OccupiedSlots.js
> +              {totalSlots.qtyBussySlots}
exacto

2022-10-21 19:47 UTC, molle98 commented on frontend_web_service/frontend/src/components/Management/OccupiedSlots.js
> +              {totalSlots.qtyBussySlots}
que misterioso que sos jajaj

2022-10-22 00:31 UTC, raquevedo requested changes
Arregla la indentacion, esta mal en todos los archivos.

Tambien tenes que actualizar tu codigo a master, tenes conflictos.

2022-10-22 00:31 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/ManagementBoard.js
> +    setAvailableSlots(data.qtyFreeSlots);
Esto no es responsabilidad del fetchData, pasalo al useEffect, aca decis que la funcion trae datos pero no tiene return.

2022-10-22 00:31 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/ManagementBoard.js
> +        { toggleState === 'status' &&
Esto pense que lo dejabamos afuera de los tabs

2022-10-22 00:31 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/TextCard.js
> +            <Card variant='outlined' sx={{ width: 2000, m: 3 }}>
Esto no es responsive

2022-10-22 00:31 UTC, raquevedo commented on frontend_web_service/frontend/src/components/Management/TextCard.js
> +                    <Typography variant="h5" component="div">
Por que usas mui aca para armar un div basico? Se podia resolver con un <h5> y un margin.

No vale la pena meter una libreria entera para esto.

2022-10-22 00:31 UTC, raquevedo commented on frontend_web_service/frontend/src/controllers/parkingController.js
> +  return await data.json();
Falta esto

2022-10-24 12:23 UTC, raquevedo commented on frontend_web_service/frontend/src/controllers/parkingController.js
> +  if (!response.ok) {
Si manejas el error desde aca no tenes como modificar el comportamiento del componente segun el error. El controller solo tiene de responsabilidad hacer un llamado y devolverte la respuesta, nada mas.

2022-10-25 12:47 UTC, closed without merging