AAC-0014-web-Styles-PrimaryVersion
raquevedo/AppArCar pull request #97
Opened 2022-10-22 14:39 UTC by JJPasso

Buenas a continuacion voy describir el contenido del PR:

- Se integraron las pantallas de **home** y **signIn** dado que habia problemas con el Responsive, ahora cuentan con el mismo.
- Se estilizo la pantalla de **ProfileSetup** NO RESPONSIVE
- Se estilizo **Dashboard** junto con el **Navbar** RESPONSIVE
- Se estilizo **SideBar** @raquevedo hay un tema con el posicionamiento de las celdas del grid x para los elementos de la barra que esta apilando de manera vertical y no horizontal para dejar a mismo nivel un icono y text. NO RESPONSIVE
- Se estilizo el formulario New Parking Garage NO RESPONSIVE
- Se estilizo los Accodions de **ListParking** cabecera y cuerpo RESPONSIVE
- Se estilizo **Profile**

Creo que no me olvido nada mas. espero correcciones y sugerencias, mañana voy a estar disponible devuelta.

2022-10-22 16:26 UTC, faballay commented
@JJPasso genial, buen detalle! 

Se me ocurren varias cosas, hagamos las faciles, las que no pensemos como resolverlas. 

1- En home: "Cercano, Economico y Rapido" seria "Cercano, Disponible y Economico"
2- Cuando me registre (cree un nuevo user) --> El alert de ERROR no tiene estilo 
3- En "Your Parkings" le pondria algun color, ahora esta en blanco. 
4- Los textos de los botones de "Your Parkings" no estan simetricos, dejemos todo en una linea o el texto arriba y el numero abajo.
5- El boton de "Manage" se tiene que ver diferente al resto, tiene que dar la sensacion de que hay que hacerle click

2022-10-22 22:55 UTC, raquevedo commented
@JJPasso Esto esta mucho mejor de lo que me esperaba con lo que me decias.

Hagamos una cosa, separemos esto en diferentes PRs por cada vista. El homepage asi como esta me parece perfecto, escala bien a diferentes tamanos de pantalla no mobile y hasta un zoom de 250 se ve bien que es razonable.

Armate un PR para: 
- Home (Listo para mergear)
- Signin (Un par de detalles que yo puedo resolver rapido)
- Dashboard (Le falta bastante laburo pero lo podemos ir viendo)
- Navbar (Esta impecable yo creo)
- Sidenav (Este no esta como habiamos dicho, creo que hay que mantener lo visual un poco mas minimalista despues del login, asi es mas facil de manejar.)

2022-10-22 23:47 UTC, ManuelArzuaga commented
en signin en los inputs de mail cuando ingresas algo queda un cuadrado blanco en los demas inputs no pasa eso @JJPasso

2022-10-22 23:50 UTC, ManuelArzuaga commented
en el navbar al costado del logo quedaron dos puntos en blanco, eso tiene que estar????

2022-10-23 19:43 UTC, JJPasso commented
> @JJPasso genial, buen detalle!
> 
> Se me ocurren varias cosas, hagamos las faciles, las que no pensemos como resolverlas.
> 
> 1- En home: "Cercano, Economico y Rapido" seria "Cercano, Disponible y Economico" 2- Cuando me registre (cree un nuevo user) --> El alert de ERROR no tiene estilo 3- En "Your Parkings" le pondria algun color, ahora esta en blanco. 4- Los textos de los botones de "Your Parkings" no estan simetricos, dejemos todo en una linea o el texto arriba y el numero abajo. 5- El boton de "Manage" se tiene que ver diferente al resto, tiene que dar la sensacion de que hay que hacerle click

Hola @faballay buen punto lo que decir en el 4 voy a alinearlos, y el punto 5 concuerdo totalmente lo voy a diferenciar con el resto ya que es un Link. 2 voy a ver que podemos hacer con los alert pero no los tengo presentes en este pr al igual que los font que son fundamentales pero son Detalles.  3 la idea es que este en blanco Fede no va a combinar muy bien otro color que no sea blanco para el contenedor ya que los accordions los botones de cada parking ya son de por si muy llamativos.

2022-10-23 19:46 UTC, JJPasso commented
> en signin en los inputs de mail cuando ingresas algo queda un cuadrado blanco en los demas inputs no pasa eso @JJPasso

que raro gracias por avisar voy a ver que onda Manu!

2022-10-23 19:48 UTC, JJPasso commented
> en el navbar al costado del logo quedaron dos puntos en blanco, eso tiene que estar????

si es de la imagen del logo eso con photoshop se puede arreglar, se me vencio la pirata asi q me tengo que bajar otra jajaja

2022-10-23 20:16 UTC, JJPasso commented
> en signin en los inputs de mail cuando ingresas algo queda un cuadrado blanco en los demas inputs no pasa eso @JJPasso
el autocompletado me esta poniendo el cuadrado blanco, eso decis? si yo escribo no cambia el fondo
![image](https://user-images.githubusercontent.com/51726371/197416094-9517ddbb-1958-4aab-80c3-19ba0e2f9724.png)

2022-10-23 20:21 UTC, ManuelArzuaga commented
> > en signin en los inputs de mail cuando ingresas algo queda un cuadrado blanco en los demas inputs no pasa eso @JJPasso
> 
> ![image](https://user-images.githubusercontent.com/51726371/197416094-9517ddbb-1958-4aab-80c3-19ba0e2f9724.png) @ManuelArzuaga el autocompletado me esta poniendo el cuadrado blanco, eso decis? si yo escribo no cambia el fondo

Si son los autocompletados los que ponen en blanco el input

2022-10-23 23:05 UTC, JJPasso commented
> > > en signin en los inputs de mail cuando ingresas algo queda un cuadrado blanco en los demas inputs no pasa eso @JJPasso
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/51726371/197416094-9517ddbb-1958-4aab-80c3-19ba0e2f9724.png) @ManuelArzuaga el autocompletado me esta poniendo el cuadrado blanco, eso decis? si yo escribo no cambia el fondo
> 
> Si son los autocompletados los que ponen en blanco el input

en ese caso no puedo hacer nada contra el poder del browser jajaja

2022-10-24 11:52 UTC, faballay requested changes
@JJPasso lo probé varias veces, una vez que me logueo la pantalla se queda en rosa y no responde mas.

2022-10-24 22:02 UTC, closed without merging