AAC-PaymentsService-0001-Create
raquevedo/AppArCar pull request #99
Opened 2022-10-22 18:44 UTC by faballay

**Setup de Payments Service**

**Devops**
- Db y service al compose principal
- Rutas en Kong

**Database**
- Entidades pmt_cardy pmt_payments

**Service**
-Endpoint para crear, borrar y obtener Tarjetas 
-Endpoint para pagar y obtener pagos 
-Auth Token

**Rabbit**
- Cada vez que se realiza un pago, se publica el mensaje en "paidReservations"

2022-10-22 22:33 UTC, raquevedo requested changes
Solo encontre una cosa, el resto anda perfecto.

Que servicios se contactarian con este? Por lo que veo hace falta el token del conductor asi que me imagino que se llama cuando pone pagar. Puede que necesitemos hacer un llamado a parking service para traer el monto en vez de mandarlo por parametro, sino se puede modificar por cualquier numero que quieran.

2022-10-22 22:33 UTC, raquevedo commented on payments_service/db/scripts/init_payments_db.sql
> +    expire_date integer NOT NULL ,
Creo que esto deberia ser un date, no tenemos como pasarle un dato valido.

2022-10-22 23:40 UTC, faballay commented on payments_service/db/scripts/init_payments_db.sql
> +    expire_date integer NOT NULL ,
Si, pensé eso del total. 
Como enviamos los datos de la reserva con el monto por Rabbit, pensé en que tome el dato directo desde ahi.
-Dejaria esta implementacion para no bloquear a Max y meto el cambio pegandole a parking en otro pr


Expire_date en las tarjetas siempre es 4 digitos: MMAA por eso lo deje como int. Pero lo cambiamos si es mas facil para laburar el date.

2022-10-23 00:31 UTC, raquevedo commented on payments_service/db/scripts/init_payments_db.sql
> +    expire_date integer NOT NULL ,
Dale, perfecto.

2022-10-23 00:32 UTC, raquevedo approved these changes

2022-10-23 01:44 UTC, billgiberti approved these changes

2022-10-23 01:44 UTC, merged